Description: myEC2Instance

Parameters:
  InstanceType:
    Description: EC2 instance configuration
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small

  EC2InstanceAmiId:
    Description: Ami identifier for the EC instance
    Type: String
    Default: ami-0747e613a2a1ff483

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: EC2InstanceAmiId
      InstanceType: 
        Ref: InstanceType

Outputs:
  PublicIp:
    Description: EC2 Instance public IP
    Value: EC2Instance.PublicIP
    